apiVersion: v1
kind: Service
metadata:
  name: vk-info-service
  namespace: vk-info
spec:
  type: NodePort
  selector:
    app: vk-info-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080