apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk-info-app
  namespace: vk-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vk-info-app
  template:
    metadata:
      labels:
        app: vk-info-app
    spec:
      containers:
        - name: vk-info-app
          image: vk-info:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: vk-info-config
                  key: SPRING_DATASOURCE_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: vk-info-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vk-info-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vk-info-secrets
                  key: JWT_SECRET
            - name: SERVER_PORT
              value: "8080"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vk-info-secrets
                  key: ADMIN_PASSWORD

