apiVersion: v1
kind: Secret
metadata:
  name: vk-info-secrets
  namespace: vk-info
type: Opaque
stringData:
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
  JWT_SECRET: <JWT_SECRET>
  ADMIN_PASSWORD: <ADMIN_PASSWORD>